### ISSUE TITLE
微信捐赠问题

### ISSUE THREAD

**Issue by AnJiuZhe** [CankingApp/MiniPay#1]
进入微信二维码扫描页面后，相册选取中并没有保存到二维码图片。还有就是希望支付宝和微信捐赠界面给个切换提示，感觉点击背景切换不太友好。

**Comment by CankingApp** [comment]
1，保存二维码问题，应该是文件读取权限问题，稍后修复。
2，如果有什么好的建议，欢迎交流～

**Comment by CankingApp** [comment]
感谢支持，后续会优化下文件保存。加上支付切换提醒～

在 2017年12月18日 下午12:09，AnJiuZhe <notifications@github.com>写道：

**Comment by CankingApp** [comment]
1.0.5版本已添加提示，及微信二维码保存问题。
