### ISSUE TITLE
这世上最不缺的就是这样的傻叼

### ISSUE THREAD

**Issue by yiyingcanfeng** [CankingApp/MiniPay#2]
![snipaste_2018-09-08_13-26-44](https://user-images.githubusercontent.com/39869232/45250688-0580cd80-b36b-11e8-9aee-f727a6363a0f.jpg)

**Comment by CankingApp** [comment]
😂😂😂

yiyingcanfeng <notifications@github.com> 于2018年9月8日周六 下午1:30写道：
